backend:
  name: git-gateway
  branch: main

media_folder: static/images/upload
public_folder: /images/upload

publish_mode: editorial_workflow

collections:
  - name: 'blog'
    label: 'blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }